
stages:
 - verify
 - build
 - push


check_jira_ticket_in_branch:
  stage: verify
  tags:
   - ci-utils
  except:
    - master
    - tags
  script:
    - /content/jira_verify


build_and_test:
  stage: build
  tags:
    - python-docker-compose-dind
  except:
    - tags
  script:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install pipenv
    - apt-get update >/dev/null
    - apt-get install -y locales >/dev/null
    - echo "en_US UTF-8" > /etc/locale.gen
    - locale-gen en_US.UTF-8
    - export LANG=en_US.UTF-8
    - export LANGUAGE=en_US:en
    - export LC_ALL=en_US.UTF-8
    - pipenv --three
    - pipenv install --dev
    - pipenv run flake8
    - pipenv run pytest -v


push_to_repo:
  stage: push
  tags:
    - rc-sys
  only:
    - master
  script:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - python setup.py sdist upload --repository devpi
  when: manual